name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instalar pylint OCA
        run: pip3 install --upgrade git+https://github.com/oca/pylint-odoo.git
      - name: Ingresar al contenedor
        run: pylint custom --disable=missing-docstring --disable=pointless-statement --disable import-error --disable=missing-final-newline
