name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inicio del servicio
        run: docker-compose up -d
      - name: Ingresar al contenedor
        run: docker exec -it logan_container bash
      - name: Test
        run: odoo -i logan_stock --log-level=test -d logan --test-enable --stop-after-init -p 10989 -r odoo -w odoo


        
